name: Show Playwright Reports
on: push

jobs:
  test:
    name: Show Playwright Reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --no-progress

      - name: Install Playwright with dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test

      - name: Publish Test report
        uses: phoenix-actions/test-reporting@v15
        with:
          name: 'Publish test report (Playwright)'
          path: 'playwright-report/results.xml'
          reporter: java-junit
          list-tests: all
          list-suites: all
          fail-on-error: true
          output-to: 'step-summary'
