name: Show Playwright Reports
on: push

jobs:
  test:
    name: Show Playwright Reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --no-progress

      - name: Install Playwright with dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test

      - name: Publish Test Report
        uses: turing85/publish-report@v2
        with:
          report-name: Tests
          report-path: 'playwright-report/index.html'