name: Show Playwright Reports
on: push

jobs:
  test:
    name: Show Playwright Reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --no-progress

      - name: Install Playwright with dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        continue-on-error: true
        run: npx playwright test

      - name: HTML Preview
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'playwright-report/index.html'
          job_summary: true