name: Show Playwright Reports  # Workflow name displayed in GitHub Actions.

on: push  # Triggers the workflow on every push event.

jobs:
  show-report:  # Defines a job for running tests and displaying reports.
    name: Show Playwright Reports  # The display name of the job.
    runs-on: ubuntu-latest  # Specifies the Ubuntu environment for execution.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*  # Uses the latest Long-Term Support (LTS) version of Node.js.
          cache: npm  # Enables automatic caching for npm dependencies.

      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm  # Specifies the directory to cache (npm's global package storage).
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci  # Installs project dependencies.

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps  # Installs required browsers and dependencies.

      - name: Run Playwright tests
        run: npx playwright test  # Executes Playwright test suite.

      - name: Publish Test report  # Displays the Playwright test report in the GitHub Actions UI.
        uses: phoenix-actions/test-reporting@v15
        with:
          name: 'Publish test report (Playwright)'  # The title of the report in the summary.
          path: 'playwright-report/results.xml'  # Specifies the test results file.
          reporter: java-junit  # Specifies the report format.
          list-tests: all  # Displays details of all tests in the summary.
          list-suites: all  # Displays test suite details.
          fail-on-error: true  # Fails the workflow if the report contains errors.
          output-to: 'step-summary'  # Displays the report in the GitHub Actions summary tab.
