name: "08 - Parallel Tests"

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Playwright with dependencies
        run: npx playwright install --with-deps

      - name: Run Playwright tests in parallel
        run: npx playwright test --browser ${{ matrix.browser }}
